version: '3.7'

services:

  elasticsearch:
    container_name: elasticsearch
    build:
      context: ../docker/elk/elasticsearch/
    volumes:
      - ../docker/elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - placesnetwork

  kibana:
    container_name: kibana
    build:
      context: ../docker/elk/kibana/
    volumes:
      - ../docker/elk/kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - placesnetwork
    depends_on:
      - elasticsearch

networks:
  placesnetwork:
    driver: bridge
    name: placesnetwork